### PR TITLE
US template tweaks

### PR DESCRIPTION
**Pull request by desbo**
Two tweaks to the US template: 
* Shorten "most shared" button text
* Ensure the header title links aren't underlined (which was happening in gmail)

### CODE REVIEW

**Comment by rrees** [comment]
Could you fill out a decent description/title explaining what this PR contains? It's impossible to understand otherwise.

**Comment by desbo** [comment]
@rrees sure

**Comment by rrees** [comment]
:+1:

**Comment by rrees** [comment]
:+1:

Thanks, the updated description is much better. If someone needs to update it later they can understand what you were trying to do.

**Pull request merged**
